- name: Configure GitHub Oauth Plugin in Jenkins
  template: >
    src=./roles/jenkins/templates/config-oauth.groovy.j2
    dest=/var/lib/jenkins/init.groovy.d/config-oauth.groovy
    owner=jenkins
    group=jenkins

- name: Configure Docker in Jenkins
  template: >
    src=./roles/jenkins/templates/config-docker.groovy.j2
    dest=/var/lib/jenkins/init.groovy.d/config-docker.groovy
    owner=jenkins
    group=jenkins
